<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HUHILSL" failures="1" tests="2" name="Test1" time="78.623" errors="0" timestamp="2025-06-15T22:27:31 IST">
  <testcase classname="tests.SearchTest" name="testSearchResultsContainApp" time="8.365"/>
  <testcase classname="tests.SearchTest" name="testSearchResultsDoNotContainApp" time="66.471">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Unexpected result for: &amp;apos;shoes&amp;apos;,
	Unexpected result for: &amp;apos;blender&amp;apos;,
	Unexpected result for: &amp;apos;tomato&amp;apos;,
	Unexpected result for: &amp;apos;soap&amp;apos;">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Unexpected result for: 'shoes',
Unexpected result for: 'blender',
Unexpected result for: 'tomato',
Unexpected result for: 'soap'
at tests.SearchTest.testSearchResultsDoNotContainApp(SearchTest.java:140)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testSearchResultsDoNotContainApp -->
</testsuite> <!-- Test1 -->
